//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTrackerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessTrackerApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _28931101_Scissors__advanced___female__small_thumbnail_3x {
            get {
                object obj = ResourceManager.GetObject("28931101-Scissors-(advanced)-(female)_small_thumbnail@3x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _bca137eb_e219_45e7_bc95_7646f86bbcd7 {
            get {
                object obj = ResourceManager.GetObject("_bca137eb-e219-45e7-bc95-7646f86bbcd7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicep Curl
        ///Ab Scissors
        ///Ab Wheel
        ///Aerobics
        ///Air Bike
        ///Arnold Press (Dumbbell)
        ///Around The World
        ///Assisted Pistol Squats
        ///Back Extension (Hyperextension)
        ///Back Extension (Machine)
        ///Back Extension (Weighted Hyperextension)
        ///Ball Slams
        ///Band Pullaparts
        ///Battle Ropes
        ///Behind the Back Bicep Wrist Curl (Barbell)
        ///Bench Dip
        ///Bench Press (Barbell)
        ///Bench Press (Cable)
        ///Bench Press (Dumbbell)
        ///Bench Press (Smith Machine)
        ///Bench Press - Close Grip (Barbell)
        ///Bench Press - Wide Grip (Barbell)
        ///Bent Over Row (Band)
        ///B [rest of string was truncated]&quot;;.
        /// </summary>
        public static string exercise_Name {
            get {
                return ResourceManager.GetString("exercise_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps
        ///Abdominals
        ///Abdominals
        ///Cardio
        ///Cardio
        ///Shoulders
        ///Chest
        ///Quadriceps
        ///Lower Back
        ///Lower Back
        ///Lower Back
        ///Full Body
        ///Shoulders
        ///Cardio
        ///Forearms
        ///Triceps
        ///Chest
        ///Chest
        ///Chest
        ///Chest
        ///Triceps
        ///Chest
        ///Upper Back
        ///Upper Back
        ///Upper Back
        ///Biceps
        ///Biceps
        ///Biceps
        ///Biceps
        ///Biceps
        ///Abdominals
        ///Abdominals
        ///Glutes
        ///Quadriceps
        ///Quadriceps
        ///Cardio
        ///Quadriceps
        ///Full Body
        ///Full Body
        ///Chest
        ///Abdominals
        ///Abdominals
        ///Chest
        ///Glutes
        ///Abdominals
        ///Abdominals
        ///Calves
        ///Calves
        ///Chest
        ///Chest
        ///Chest
        ///Chest
        ///Chest
        ///Chest
        ///Che [rest of string was truncated]&quot;;.
        /// </summary>
        public static string muscle_group {
            get {
                return ResourceManager.GetString("muscle-group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap new_text_logo_repify {
            get {
                object obj = ResourceManager.GetObject("new text logo repify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap new_text_logo_repify_small_ {
            get {
                object obj = ResourceManager.GetObject("new text logo repify(small)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Repify_LOGO_BWpng {
            get {
                object obj = ResourceManager.GetObject("Repify LOGO BWpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
